$('.owl-carousel').owlCarousel({
    loop:false,
    margin:20,
    nav:false,
    dots:false,
    responsive:{
        0:{
            items:1
        },
        480:{
            items:2
        },
        768:{
            items:3
        },
        992:{
            items:4
        },
        1200:{
            items:5
        },
        1440:{
            items:6
        },
        1920:{
            items:8
        }
    }
})