$('.owl-carousel').owlCarousel({
    loop:false,
    margin:20,
    nav:false,
    dots:false,
    responsive:{
        0:{
            items:1
        },
        576:{
            items:2
        },
        768:{
            items:3
        },
        992:{
            items:4
        },
        1000:{
            items:6
        }
    }
})